"""Agent repository interfaces."""

import uuid
from typing import Protocol

from kitaru.server.application.models.agent import AgentFilter
from kitaru.server.application.models.agent_version import AgentVersionFilter
from kitaru.server.domain.agent import Agent
from kitaru.server.domain.agent_version import AgentVersion


class AgentRepository(Protocol):
    """Agent persistence operations."""

    async def create(self, agent: Agent) -> Agent: ...
    async def get(self, agent_id: uuid.UUID, exclusive: bool = False) -> Agent: ...
    async def get_by_name(self, name: str) -> Agent: ...
    async def query(
        self, agent_filter: AgentFilter
    ) -> tuple[list[Agent], str | None]: ...
    async def update(self, agent: Agent) -> Agent: ...
    async def delete(self, agent_id: uuid.UUID) -> None: ...
    async def next_version(self, agent_id: uuid.UUID) -> int: ...
    async def version_is_frozen(self, version_id: uuid.UUID) -> bool: ...


class AgentVersionRepository(Protocol):
    """Agent-version persistence operations."""

    async def create(self, version: AgentVersion) -> AgentVersion: ...
    async def get(self, version_id: uuid.UUID) -> AgentVersion: ...
    async def get_by_version(
        self, agent_id: uuid.UUID, version: int
    ) -> AgentVersion: ...
    async def get_many(self, ids: list[uuid.UUID]) -> dict[uuid.UUID, AgentVersion]: ...
    async def query(
        self, version_filter: AgentVersionFilter
    ) -> tuple[list[AgentVersion], str | None]: ...
    async def update(self, version: AgentVersion) -> AgentVersion: ...
    async def delete(self, version_id: uuid.UUID) -> None: ...
