"""Plugin registry repository interface."""

import uuid
from typing import Protocol

from kitaru.server.application.models.plugin import (
    PluginFilter,
    PluginVersionFilter,
)
from kitaru.server.domain.plugin import Plugin, PluginKind, PluginVersion


class PluginRepository(Protocol):
    """Plugin and plugin-version persistence operations."""

    async def create(self, plugin: Plugin) -> Plugin: ...
    async def get(self, plugin_id: uuid.UUID) -> Plugin: ...
    async def get_by_name(self, kind: PluginKind, name: str) -> Plugin: ...
    async def query(
        self, plugin_filter: PluginFilter
    ) -> tuple[list[Plugin], str | None]: ...
    async def update(self, plugin: Plugin) -> Plugin: ...
    async def delete(self, plugin_id: uuid.UUID) -> None: ...
    async def next_version(self, plugin_id: uuid.UUID) -> int: ...
    async def create_version(self, version: PluginVersion) -> PluginVersion: ...
    async def get_version(self, version_id: uuid.UUID) -> PluginVersion: ...
    async def get_version_number(
        self, plugin_id: uuid.UUID, version: int
    ) -> PluginVersion: ...
    async def get_many_versions(
        self, ids: list[uuid.UUID]
    ) -> dict[uuid.UUID, PluginVersion]: ...
    async def query_versions(
        self, version_filter: PluginVersionFilter
    ) -> tuple[list[PluginVersion], str | None]: ...
    async def update_version(self, version: PluginVersion) -> PluginVersion: ...
    async def delete_version(self, version_id: uuid.UUID) -> None: ...
