"""Replay repository interface."""

import uuid
from typing import Protocol

from kitaru.server.application.models.replay import ReplayFilter
from kitaru.server.domain.replay import Replay, ReplayStatus
from kitaru.server.domain.replay_config import ReplayConfig


class ReplayRepository(Protocol):
    """Replay and replay-configuration persistence operations."""

    async def create(
        self, replay: Replay, config: ReplayConfig
    ) -> tuple[Replay, ReplayConfig]: ...
    async def get(self, replay_id: uuid.UUID, exclusive: bool = False) -> Replay: ...
    async def get_by_job(self, job_id: uuid.UUID) -> Replay | None: ...
    async def get_config(self, config_id: uuid.UUID) -> ReplayConfig: ...
    async def query(
        self, replay_filter: ReplayFilter
    ) -> tuple[list[Replay], str | None]: ...
    async def update(self, replay: Replay) -> Replay: ...
    async def count_unsettled(self, run_id: uuid.UUID) -> int: ...
    async def count_statuses(self, run_id: uuid.UUID) -> dict[ReplayStatus, int]: ...
    async def list_job_ids(self, run_id: uuid.UUID) -> list[uuid.UUID]: ...
