"""Task repository interface."""

import uuid
from datetime import datetime
from typing import Protocol

from kitaru.api_models.v1.task import WorkerScope
from kitaru.server.application.models.task import TaskFilter
from kitaru.server.domain.task import Task


class TaskRepository(Protocol):
    """Task queue persistence operations."""

    async def create(self, task: Task) -> Task: ...
    async def get(self, task_id: uuid.UUID, exclusive: bool = False) -> Task: ...
    async def get_many(self, ids: list[uuid.UUID]) -> dict[uuid.UUID, Task]: ...
    async def query(self, task_filter: TaskFilter) -> tuple[list[Task], str | None]: ...
    async def update(self, task: Task, expected_attempt: int | None = None) -> Task: ...
    async def claim_pending(
        self, worker_id: uuid.UUID, scope: WorkerScope, max_tasks: int
    ) -> list[Task]: ...
    async def list_job_tasks(
        self, job_id: uuid.UUID, exclusive: bool = False
    ) -> list[Task]: ...
    async def stale(self, stale_before: datetime, limit: int) -> list[Task]: ...
    async def heartbeat(
        self, worker_id: uuid.UUID, task_ids: list[uuid.UUID], now: datetime
    ) -> list[uuid.UUID]: ...
    async def completed_evaluator_exists(
        self, session_id: uuid.UUID, plugin_version_id: uuid.UUID
    ) -> bool: ...
