[files]
extend-exclude = [
    "*.json",
    "*.js",
    "*.ipynb",
    "uv.lock",
]

[default.extend-identifiers]
HashiCorp = "HashiCorp"

[default.extend-words]
# Don't correct the surname "Teh"
aks = "aks"

[default]
locale = "en-us"
