apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kitaru.fullname" . }}
  labels:
    {{- include "kitaru.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kitaru.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret-environment: {{ .Values.server.secretEnvironment | toJson | sha256sum }}
        checksum/environment: {{ .Values.server.environment | toJson | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kitaru.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kitaru.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "kitaru.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "kitaru.environment" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
