{{- if .Values.server.secretEnvironment }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kitaru.fullname" . }}-migration
  labels:
    {{- include "kitaru.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-10"
type: Opaque
stringData:
  {{- range $name, $value := .Values.server.secretEnvironment }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
