{{- if .Values.server.secretEnvironment }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kitaru.fullname" . }}
  labels:
    {{- include "kitaru.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.server.secretEnvironment }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
