apiVersion: v1
kind: Service
metadata:
  name: {{ include "kitaru.fullname" . }}
  labels:
    {{- include "kitaru.labels" . | nindent 4 }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "kitaru.serverSelectorLabels" . | nindent 4 }}
