"""Extract the Kitaru Python SDK public API to JSON for docs generation.

Uses griffe (via fumapy) to introspect the kitaru package and produces a
filtered JSON file containing only the public API surface. The JSON is
consumed by the Node-side conversion script (docs/scripts/convert-sdk-docs.mjs)
to produce MDX pages for FumaDocs.

The two-script split exists because griffe is Python-only while the MDX
conversion uses fumadocs-python's Node API. In CI, this script runs after
pnpm install (so fumapy can be pip-installed from the npm package).

Requires: fumapy (pip install ./docs/node_modules/fumadocs-python)

Output: docs/.generated/sdk-api.json (gitignored intermediate artifact)

Usage:
    uv run python scripts/generate_sdk_docs.py
"""

from __future__ import annotations

import ast
import json
import re
import shutil
from pathlib import Path
from typing import Any

try:
    import griffe
    from fumapy.mksource import CustomEncoder, parse_module
    from griffe_typingdoc import TypingDocExtension

    _HAS_GRIFFE = True
except ImportError:
    _HAS_GRIFFE = False

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "docs" / ".generated"
OUTPUT_FILE = OUTPUT_DIR / "sdk-api.json"

# GitBook output. Committed plain-Markdown reference under docs/book/reference/
# python/ (no React components, unlike the FumaDocs convert step), with the
# sidebar fragment spliced into toc.md between SDK markers.
GITBOOK_DIR = REPO_ROOT / "docs" / "book" / "reference" / "python"
GITBOOK_TOC = REPO_ROOT / "docs" / "book" / "toc.md"
SDK_TOC_START = "<!-- SDK:START (generated by generate_sdk_docs.py) -->"
SDK_TOC_END = "<!-- SDK:END -->"

# Modules to include in the SDK reference. Only explicitly listed modules
# become published reference pages. This prevents CLI internals, empty
# scaffolding, and private modules from leaking into the docs.
PUBLIC_MODULES = ["kitaru"]

# Submodules to exclude from the reference even if they appear in a
# public module's tree. These have their own docs or are not public.
EXCLUDED_SUBMODULES = {"cli", "adapters", "runtime"}


def _is_private(name: str) -> bool:
    """Check if a module/symbol name is private by convention."""
    return name.rsplit(".", 1)[-1].startswith("_")


def _is_documented_member(name: str) -> bool:
    """Return whether a member should appear in generated docs."""
    return name == "__init__" or not _is_private(name)


def _exported_names(data: dict) -> set[str] | None:
    """Return ``__all__`` names when the module defines them."""
    for attr in data.get("attributes", []):
        if attr.get("name") != "__all__":
            continue
        raw_value = attr.get("value")
        if not isinstance(raw_value, str):
            return None
        try:
            parsed = ast.literal_eval(raw_value)
        except (SyntaxError, ValueError):
            return None
        if isinstance(parsed, list) and all(isinstance(name, str) for name in parsed):
            return {str(name) for name in parsed}
        return None
    return None


def _filter_attributes(
    attributes: list[dict],
    *,
    exported_names: set[str] | None = None,
) -> list[dict]:
    """Filter a list of serialized attributes to public ones only."""
    filtered: list[dict] = []
    for attr in attributes:
        name = attr.get("name", "")
        if name == "__all__":
            continue
        if exported_names is not None:
            if name not in exported_names:
                continue
        elif _is_private(name):
            continue
        filtered.append(attr)
    return filtered


def _filter_class(data: dict) -> dict:
    """Filter private methods and attributes from one serialized class."""
    filtered = dict(data)
    filtered["functions"] = {
        name: func
        for name, func in data.get("functions", {}).items()
        if _is_documented_member(name)
    }
    filtered["classes"] = {
        name: _filter_class(cls)
        for name, cls in data.get("classes", {}).items()
        if _is_documented_member(name)
    }
    filtered["attributes"] = _filter_attributes(data.get("attributes", []))
    filtered["inherited_members"] = {
        name: member
        for name, member in data.get("inherited_members", {}).items()
        if _is_documented_member(name)
    }
    return filtered


def _filter_module(data: dict, *, is_root: bool = False) -> dict:
    """Filter a module dict to remove excluded and private submodules.

    For the root module, also promotes re-exported symbols from private
    submodules to the top level (matching __all__ behavior).
    """
    filtered = dict(data)
    exported_names = _exported_names(data) if is_root else None

    # Collect symbols from private submodules before removing them
    promoted_classes: dict = {}
    promoted_functions: dict = {}

    for name, submod in list(data.get("modules", {}).items()):
        if name in EXCLUDED_SUBMODULES:
            continue
        if _is_private(name) and is_root:
            # Promote public symbols from private modules to root
            promoted_classes.update(
                {
                    symbol_name: _filter_class(symbol)
                    for symbol_name, symbol in submod.get("classes", {}).items()
                    if exported_names is not None
                    and symbol_name in exported_names
                    and _is_documented_member(symbol_name)
                }
            )
            promoted_functions.update(
                {
                    symbol_name: symbol
                    for symbol_name, symbol in submod.get("functions", {}).items()
                    if exported_names is not None
                    and symbol_name in exported_names
                    and _is_documented_member(symbol_name)
                }
            )

    # Remove excluded and private submodules
    filtered["modules"] = {
        name: _filter_module(submod)
        for name, submod in data.get("modules", {}).items()
        if name not in EXCLUDED_SUBMODULES and not _is_private(name)
    }

    filtered["classes"] = {
        name: _filter_class(cls)
        for name, cls in data.get("classes", {}).items()
        if _is_documented_member(name)
        and (exported_names is None or name in exported_names)
    }
    filtered["functions"] = {
        name: func
        for name, func in data.get("functions", {}).items()
        if _is_documented_member(name)
        and (exported_names is None or name in exported_names)
    }

    # Merge promoted symbols into root
    if is_root:
        existing_classes = dict(filtered["classes"])
        existing_classes.update(promoted_classes)
        filtered["classes"] = existing_classes

        existing_functions = dict(filtered["functions"])
        existing_functions.update(promoted_functions)
        filtered["functions"] = existing_functions

    filtered["attributes"] = _filter_attributes(
        data.get("attributes", []),
        exported_names=exported_names,
    )

    return filtered


def extract_api(module_name: str) -> dict:
    """Extract the public API of a Python module using griffe."""
    if not _HAS_GRIFFE:
        msg = (
            "Missing dependency: fumapy (and griffe).\n"
            "  Install: uv pip install ./docs/node_modules/fumadocs-python\n"
            "  (requires 'pnpm install' in docs/ first)"
        )
        raise ImportError(msg)
    extensions = griffe.load_extensions(TypingDocExtension)
    loaded = griffe.load(
        module_name,
        docstring_parser="google",
        store_source=True,
        extensions=extensions,
    )
    if not isinstance(loaded, griffe.Object):
        msg = f"Expected griffe.Object, got {type(loaded).__name__}"
        raise TypeError(msg)

    parsed = parse_module(loaded)

    # Round-trip through JSON to get plain dicts (CustomEncoder handles
    # griffe Expr objects, Path objects, etc.)
    raw = json.loads(json.dumps(parsed, cls=CustomEncoder))
    return raw


# ---------------------------------------------------------------------------
# GitBook rendering — filtered API dict to plain Markdown pages
# ---------------------------------------------------------------------------


def _desc_text(desc: Any) -> str:
    """Normalize a description field (string or list of fragments) to text."""
    if desc is None:
        return ""
    if isinstance(desc, str):
        return desc.strip()
    if isinstance(desc, list):
        parts: list[str] = []
        for frag in desc:
            if isinstance(frag, dict):
                value = frag.get("value")
                if value:
                    parts.append(str(value))
        return " ".join(parts).strip()
    return str(desc).strip()


def _first_line(text: str) -> str:
    """First non-empty line of a block of text, for frontmatter descriptions."""
    for line in text.splitlines():
        if line.strip():
            return line.strip()
    return ""


def _frontmatter(description: str, *, icon: str | None = None) -> str:
    safe = description.replace('"', '\\"') or "Kitaru Python SDK reference."
    icon_line = f"icon: {icon}\n" if icon else ""
    return f'---\ndescription: "{safe}"\n{icon_line}---\n'


def _is_public_param(param: dict) -> bool:
    """Exclude method receivers and private (underscore) parameters."""
    name = param.get("name", "")
    return name not in {"self", "cls"} and not name.startswith("_")


def _params_table(parameters: list[dict]) -> list[str]:
    """Render a parameters table, skipping receivers and private params."""
    rows = [p for p in parameters if _is_public_param(p)]
    if not rows:
        return []
    lines = [
        "**Parameters**",
        "",
        "| Name | Type | Default | Description |",
        "| --- | --- | --- | --- |",
    ]
    for p in rows:
        name = f"`{p.get('name', '')}`"
        annotation = p.get("annotation")
        type_str = f"`{annotation}`" if annotation else ""
        value = p.get("value")
        default = f"`{value}`" if value is not None else ""
        desc = _desc_text(p.get("description")).replace("\n", " ")
        lines.append(f"| {name} | {type_str} | {default} | {desc} |")
    lines.append("")
    return lines


def _clean_signature(signature: str) -> str:
    """Drop method receivers (self/cls) and private kwargs from a signature."""
    s = re.sub(r"\(\s*(?:self|cls)\s*,\s*", "(", signature)
    s = re.sub(r"\(\s*(?:self|cls)\s*\)", "()", s)
    # Remove private keyword params like ", _require_project=True".
    s = re.sub(r",\s*_\w+(?:\s*:\s*[^,=()]+)?(?:\s*=\s*[^,()]+)?", "", s)
    return s


def _render_callable(name: str, fn: dict, heading: str) -> list[str]:
    """Render a function or method as Markdown."""
    signature = _clean_signature(fn.get("signature") or "()")
    lines = [
        f"{heading} `{name}`",
        "",
        "```python",
        f"{name}{signature}",
        "```",
        "",
    ]
    description = _desc_text(fn.get("description"))
    if description:
        lines += [description, ""]
    lines += _params_table(fn.get("parameters") or [])
    returns = fn.get("returns") or {}
    ret_desc = _desc_text(returns.get("description"))
    if ret_desc:
        lines += [f"**Returns:** {ret_desc}", ""]
    return lines


def _render_class(name: str, cls: dict, heading: str = "##") -> list[str]:
    """Render a class with its attributes and public methods."""
    lines = [f"{heading} `{name}`", ""]
    description = _desc_text(cls.get("description"))
    if description:
        lines += [description, ""]

    attributes = [a for a in cls.get("attributes", []) if a.get("name") != "__all__"]
    if attributes:
        lines += [
            "**Attributes**",
            "",
            "| Name | Type | Description |",
            "| --- | --- | --- |",
        ]
        for a in attributes:
            annotation = a.get("annotation")
            type_str = f"`{annotation}`" if annotation else ""
            desc = _desc_text(a.get("description")).replace("\n", " ")
            lines.append(f"| `{a.get('name', '')}` | {type_str} | {desc} |")
        lines.append("")

    methods = {n: m for n, m in cls.get("functions", {}).items() if n != "__init__"}
    if "__init__" in cls.get("functions", {}):
        # Surface the constructor signature inline rather than as a method.
        init = cls["functions"]["__init__"]
        sig = _clean_signature(init.get("signature") or "()")
        lines += ["**Constructor**", "", "```python", f"{name}{sig}", "```", ""]
        lines += _params_table(init.get("parameters") or [])
    for mname, method in methods.items():
        lines += _render_callable(f"{name}.{mname}", method, "###")
    return lines


def _render_module_page(name: str, module: dict) -> str:
    description = _desc_text(module.get("description"))
    lines = [
        _frontmatter(_first_line(description) or f"`kitaru.{name}` reference."),
        "",
    ]
    lines += [f"# `kitaru.{name}`", ""]
    if description:
        lines += [description, ""]
    for fname, fn in module.get("functions", {}).items():
        lines += _render_callable(fname, fn, "##")
    for cname, cls in module.get("classes", {}).items():
        lines += _render_class(cname, cls, "##")
    return "\n".join(lines).rstrip() + "\n"


def _render_root_class_page(name: str, cls: dict) -> str:
    description = (
        _first_line(_desc_text(cls.get("description"))) or f"`{name}` reference."
    )
    body = _render_class(name, cls, "#")
    return _frontmatter(description) + "\n" + "\n".join(body).rstrip() + "\n"


def _render_index(
    modules: list[tuple[str, str]], root_classes: list[tuple[str, str]]
) -> str:
    lines = [
        _frontmatter("Kitaru Python SDK reference.", icon="code"),
        "",
        "# Python SDK Reference",
        "",
        "Generated reference for the public `kitaru` API. See the "
        "[Core Concepts](../../concepts/README.md) and [Guides](../../guides/"
        "configuration.md) for usage in context.",
        "",
    ]
    if modules:
        lines += ["## Modules", "", "| Module | Description |", "| --- | --- |"]
        for name, desc in modules:
            lines.append(f"| [`kitaru.{name}`]({name}.md) | {desc} |")
        lines.append("")
    if root_classes:
        lines += ["## Classes", "", "| Class | Description |", "| --- | --- |"]
        for name, desc in root_classes:
            lines.append(f"| [`{name}`]({name.lower()}.md) | {desc} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _public_api_names() -> set[str]:
    """The symbols re-exported in ``kitaru.__all__`` — the documented surface."""
    import kitaru

    return set(getattr(kitaru, "__all__", []))


def _restrict_to_public(module: dict, public: set[str]) -> dict:
    """Keep only ``__all__`` functions/classes from a submodule."""
    restricted = dict(module)
    restricted["functions"] = {
        n: f for n, f in module.get("functions", {}).items() if n in public
    }
    restricted["classes"] = {
        n: c for n, c in module.get("classes", {}).items() if n in public
    }
    restricted["attributes"] = []
    return restricted


def write_gitbook_sdk(filtered: dict) -> None:
    """Write the committed GitBook SDK reference tree and splice toc.md."""
    if GITBOOK_DIR.exists():
        shutil.rmtree(GITBOOK_DIR)
    GITBOOK_DIR.mkdir(parents=True, exist_ok=True)

    public = _public_api_names()

    modules: list[tuple[str, str]] = []
    for name, module in filtered.get("modules", {}).items():
        restricted = _restrict_to_public(module, public)
        if not (restricted["functions"] or restricted["classes"]):
            continue
        (GITBOOK_DIR / f"{name}.md").write_text(_render_module_page(name, restricted))
        modules.append((name, _first_line(_desc_text(module.get("description")))))

    root_classes: list[tuple[str, str]] = []
    for name, cls in sorted(filtered.get("classes", {}).items()):
        if name not in public:
            continue
        (GITBOOK_DIR / f"{name.lower()}.md").write_text(
            _render_root_class_page(name, cls)
        )
        root_classes.append((name, _first_line(_desc_text(cls.get("description")))))

    (GITBOOK_DIR / "README.md").write_text(_render_index(modules, root_classes))

    fragment_lines = ["* [Python SDK](reference/python/README.md)"]
    for name, _ in modules:
        fragment_lines.append(f"  * [kitaru.{name}](reference/python/{name}.md)")
    for name, _ in root_classes:
        fragment_lines.append(f"  * [{name}](reference/python/{name.lower()}.md)")
    fragment = "\n".join(fragment_lines)

    toc = GITBOOK_TOC.read_text()
    pattern = re.compile(
        re.escape(SDK_TOC_START) + r".*?" + re.escape(SDK_TOC_END), re.DOTALL
    )
    if not pattern.search(toc):
        raise SystemExit(f"SDK toc markers not found in {GITBOOK_TOC}")
    GITBOOK_TOC.write_text(
        pattern.sub(f"{SDK_TOC_START}\n{fragment}\n{SDK_TOC_END}", toc)
    )
    count = len(modules) + len(root_classes)
    print(
        f"Generated {count} GitBook SDK pages in "
        f"{GITBOOK_DIR.relative_to(REPO_ROOT)}/ and spliced toc.md"
    )


def main() -> int:
    """Extract and filter the Kitaru SDK API to JSON."""
    if not _HAS_GRIFFE:
        print("ERROR: Missing dependency: fumapy (and griffe).")
        print("  Install: uv pip install ./docs/node_modules/fumadocs-python")
        print("  (requires 'pnpm install' in docs/ first)")
        return 1

    for module_name in PUBLIC_MODULES:
        try:
            __import__(module_name)
        except ImportError:
            print(f"ERROR: Cannot import '{module_name}'. Is it installed?")
            return 1

    print("Extracting SDK API...")
    raw = extract_api("kitaru")
    filtered = _filter_module(raw, is_root=True)

    # Validate: if we ended up with nothing meaningful, fail loudly
    has_content = (
        filtered.get("classes") or filtered.get("functions") or filtered.get("modules")
    )
    if not has_content:
        print("WARNING: No public API surface found. Skipping SDK docs generation.")
        print("  This is expected if the SDK has no public symbols yet.")
        return 0

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(json.dumps(filtered, indent=2) + "\n")

    write_gitbook_sdk(filtered)

    rel = OUTPUT_FILE.relative_to(REPO_ROOT)
    n_classes = len(filtered.get("classes", {}))
    n_functions = len(filtered.get("functions", {}))
    n_modules = len(filtered.get("modules", {}))
    print(
        f"Extracted {n_classes} classes, {n_functions} functions, {n_modules} modules"
    )
    print(f"Wrote {rel}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
