"""Synthetic orders, policies, shipments, and support tickets."""

from decimal import Decimal

from returns_agent.models import (
    Order,
    ReturnPolicy,
    ShippingStatus,
    TicketInput,
)

POLICIES = {
    "footwear": ReturnPolicy(
        category="footwear",
        window_days=30,
        defective_full_refund=True,
        unused_return=True,
        final_sale_defect_exception=True,
        human_approval_threshold=Decimal("150.00"),
    ),
    "apparel": ReturnPolicy(
        category="apparel",
        window_days=30,
        defective_full_refund=True,
        unused_return=True,
        final_sale_defect_exception=True,
        human_approval_threshold=Decimal("150.00"),
    ),
    "accessories": ReturnPolicy(
        category="accessories",
        window_days=14,
        defective_full_refund=True,
        unused_return=True,
        final_sale_defect_exception=False,
        human_approval_threshold=Decimal("100.00"),
    ),
    "luggage": ReturnPolicy(
        category="luggage",
        window_days=45,
        defective_full_refund=True,
        unused_return=True,
        final_sale_defect_exception=True,
        human_approval_threshold=Decimal("200.00"),
    ),
}

ORDERS = {
    "48213": Order(
        order_id="48213",
        email="dana@example.test",
        product="Merino Runners",
        category="footwear",
        amount_paid=Decimal("98.00"),
        status="delivered",
        days_since_delivery=21,
        tracking_no="TRACK-48213",
    ),
    "48214": Order(
        order_id="48214",
        email="leo@example.test",
        product="Archive Hoodie",
        category="apparel",
        amount_paid=Decimal("64.00"),
        status="delivered",
        days_since_delivery=12,
        final_sale=True,
        tracking_no="TRACK-48214",
    ),
    "48215": Order(
        order_id="48215",
        email="maya@example.test",
        product="Everyday Tote",
        category="accessories",
        amount_paid=Decimal("48.00"),
        status="delivered",
        days_since_delivery=20,
        tracking_no="TRACK-48215",
    ),
    "48216": Order(
        order_id="48216",
        email="sam@example.test",
        product="Aluminum Carry-On",
        category="luggage",
        amount_paid=Decimal("280.00"),
        status="delivered",
        days_since_delivery=8,
        tracking_no="TRACK-48216",
    ),
    "48217": Order(
        order_id="48217",
        email="chris@example.test",
        product="Trail Backpack",
        category="accessories",
        amount_paid=Decimal("75.00"),
        status="shipped",
        days_since_delivery=None,
        tracking_no="TRACK-48217",
    ),
    "48218": Order(
        order_id="48218",
        email="morgan@example.test",
        product="Field Jacket",
        category="apparel",
        amount_paid=Decimal("120.00"),
        status="delivered",
        days_since_delivery=5,
        tracking_no="TRACK-48218",
        risk_flags=["account_takeover_review"],
    ),
    "48219": Order(
        order_id="48219",
        email="alex@example.test",
        product="Canvas Slip-Ons",
        category="footwear",
        amount_paid=Decimal("82.00"),
        status="delivered",
        days_since_delivery=9,
        tracking_no="TRACK-48219",
        already_refunded=True,
    ),
    "48220": Order(
        order_id="48220",
        email="jamie@example.test",
        product="Two Essential Tees",
        category="apparel",
        amount_paid=Decimal("80.00"),
        status="delivered",
        days_since_delivery=6,
        tracking_no="TRACK-48220",
    ),
    "48221": Order(
        order_id="48221",
        email="pat@example.test",
        product="City Loafers",
        category="footwear",
        amount_paid=Decimal("110.00"),
        status="delivered",
        days_since_delivery=10,
        tracking_no="TRACK-48221",
    ),
    "48222": Order(
        order_id="48222",
        email="riley@example.test",
        product="Merino Runners",
        category="footwear",
        amount_paid=Decimal("98.00"),
        status="delivered",
        days_since_delivery=18,
        tracking_no="TRACK-48222",
    ),
    "48230": Order(
        order_id="48230",
        email="nora@example.test",
        product="Weekender Duffel",
        category="luggage",
        amount_paid=Decimal("240.00"),
        status="delivered",
        days_since_delivery=6,
        tracking_no="TRACK-48230",
    ),
    "48231": Order(
        order_id="48231",
        email="omar@example.test",
        product="Leather Chelsea Boots",
        category="footwear",
        amount_paid=Decimal("210.00"),
        status="delivered",
        days_since_delivery=12,
        tracking_no="TRACK-48231",
    ),
    "48232": Order(
        order_id="48232",
        email="ines@example.test",
        product="Down Parka",
        category="apparel",
        amount_paid=Decimal("320.00"),
        status="delivered",
        days_since_delivery=9,
        tracking_no="TRACK-48232",
    ),
    "48233": Order(
        order_id="48233",
        email="theo@example.test",
        product="Hardshell Checked Bag",
        category="luggage",
        amount_paid=Decimal("360.00"),
        status="delivered",
        days_since_delivery=20,
        tracking_no="TRACK-48233",
    ),
    "48234": Order(
        order_id="48234",
        email="lena@example.test",
        product="Leather Messenger Bag",
        category="accessories",
        amount_paid=Decimal("165.00"),
        status="delivered",
        days_since_delivery=7,
        tracking_no="TRACK-48234",
    ),
    "48235": Order(
        order_id="48235",
        email="kofi@example.test",
        product="Trail Running Shoes",
        category="footwear",
        amount_paid=Decimal("175.00"),
        status="delivered",
        days_since_delivery=15,
        tracking_no="TRACK-48235",
    ),
    "48236": Order(
        order_id="48236",
        email="yuki@example.test",
        product="Wool Overcoat",
        category="apparel",
        amount_paid=Decimal("280.00"),
        status="delivered",
        days_since_delivery=11,
        tracking_no="TRACK-48236",
    ),
    "48237": Order(
        order_id="48237",
        email="ben@example.test",
        product="Canvas Sneakers",
        category="footwear",
        amount_paid=Decimal("65.00"),
        status="delivered",
        days_since_delivery=5,
        tracking_no="TRACK-48237",
    ),
    "48238": Order(
        order_id="48238",
        email="ava@example.test",
        product="Crew Socks 3-Pack",
        category="apparel",
        amount_paid=Decimal("24.00"),
        status="delivered",
        days_since_delivery=3,
        tracking_no="TRACK-48238",
    ),
    "48239": Order(
        order_id="48239",
        email="luis@example.test",
        product="Card Wallet",
        category="accessories",
        amount_paid=Decimal("38.00"),
        status="delivered",
        days_since_delivery=6,
        tracking_no="TRACK-48239",
    ),
    "48240": Order(
        order_id="48240",
        email="zoe@example.test",
        product="Rain Jacket",
        category="apparel",
        amount_paid=Decimal("95.00"),
        status="delivered",
        days_since_delivery=14,
        tracking_no="TRACK-48240",
    ),
    "48241": Order(
        order_id="48241",
        email="finn@example.test",
        product="Cabin Tote",
        category="luggage",
        amount_paid=Decimal("120.00"),
        status="delivered",
        days_since_delivery=25,
        tracking_no="TRACK-48241",
    ),
    "48242": Order(
        order_id="48242",
        email="mia@example.test",
        product="Slip-On Sandals",
        category="footwear",
        amount_paid=Decimal("45.00"),
        status="delivered",
        days_since_delivery=8,
        tracking_no="TRACK-48242",
    ),
    "48243": Order(
        order_id="48243",
        email="raj@example.test",
        product="Knit Beanie",
        category="accessories",
        amount_paid=Decimal("22.00"),
        status="delivered",
        days_since_delivery=4,
        tracking_no="TRACK-48243",
    ),
    "48244": Order(
        order_id="48244",
        email="eve@example.test",
        product="Linen Shirt",
        category="apparel",
        amount_paid=Decimal("58.00"),
        status="delivered",
        days_since_delivery=10,
        tracking_no="TRACK-48244",
    ),
    "48245": Order(
        order_id="48245",
        email="jon@example.test",
        product="Desert Boots",
        category="footwear",
        amount_paid=Decimal("130.00"),
        status="delivered",
        days_since_delivery=20,
        tracking_no="TRACK-48245",
    ),
    "48246": Order(
        order_id="48246",
        email="kim@example.test",
        product="Travel Organizer",
        category="accessories",
        amount_paid=Decimal("35.00"),
        status="shipped",
        days_since_delivery=None,
        tracking_no="TRACK-48246",
    ),
    "48247": Order(
        order_id="48247",
        email="tom@example.test",
        product="Running Shorts",
        category="apparel",
        amount_paid=Decimal("40.00"),
        status="shipped",
        days_since_delivery=None,
        tracking_no="TRACK-48247",
    ),
    "48248": Order(
        order_id="48248",
        email="sara@example.test",
        product="Packable Daypack",
        category="luggage",
        amount_paid=Decimal("85.00"),
        status="shipped",
        days_since_delivery=None,
        tracking_no="TRACK-48248",
    ),
    "48249": Order(
        order_id="48249",
        email="dev@example.test",
        product="Leather Belt",
        category="accessories",
        amount_paid=Decimal("55.00"),
        status="delivered",
        days_since_delivery=30,
        tracking_no="TRACK-48249",
    ),
    "48250": Order(
        order_id="48250",
        email="amy@example.test",
        product="Chino Trousers",
        category="apparel",
        amount_paid=Decimal("70.00"),
        status="delivered",
        days_since_delivery=52,
        tracking_no="TRACK-48250",
    ),
    "48251": Order(
        order_id="48251",
        email="max@example.test",
        product="Outlet Sneakers",
        category="footwear",
        amount_paid=Decimal("49.00"),
        status="delivered",
        days_since_delivery=7,
        final_sale=True,
        tracking_no="TRACK-48251",
    ),
    "48252": Order(
        order_id="48252",
        email="liv@example.test",
        product="Yoga Leggings",
        category="apparel",
        amount_paid=Decimal("62.00"),
        status="delivered",
        days_since_delivery=9,
        already_refunded=True,
        tracking_no="TRACK-48252",
    ),
    "48253": Order(
        order_id="48253",
        email="gus@example.test",
        product="Laptop Sleeve",
        category="accessories",
        amount_paid=Decimal("42.00"),
        status="shipped",
        days_since_delivery=None,
        tracking_no="TRACK-48253",
    ),
}

SHIPMENTS = {
    "TRACK-48217": ShippingStatus(
        tracking_no="TRACK-48217",
        status="lost",
        detail="Carrier investigation closed: package lost in transit.",
    ),
    "TRACK-48246": ShippingStatus(
        tracking_no="TRACK-48246",
        status="lost",
        detail="Carrier investigation closed: package lost in transit.",
    ),
    "TRACK-48247": ShippingStatus(
        tracking_no="TRACK-48247",
        status="lost",
        detail="Carrier investigation closed: package lost in transit.",
    ),
    "TRACK-48248": ShippingStatus(
        tracking_no="TRACK-48248",
        status="lost",
        detail="Carrier investigation closed: package lost in transit.",
    ),
    "TRACK-48253": ShippingStatus(
        tracking_no="TRACK-48253",
        status="in_transit",
        detail="Package departed the regional hub and is due in two days.",
    ),
}


def _ticket(
    ticket_id: str,
    customer_name: str,
    email: str,
    subject: str,
    body: str,
) -> TicketInput:
    """Create one compact synthetic support email."""
    return TicketInput(
        ticket_id=ticket_id,
        customer_name=customer_name,
        email=email,
        subject=subject,
        body=body,
    )


CASES = (
    _ticket(
        "ticket-001",
        "Dana",
        "dana@example.test",
        "Hole in my Merino Runners",
        (
            "Hi, I ordered the Merino Runners (order #48213) three weeks "
            "ago and they arrived with a hole in the left shoe. I'd like "
            "a refund. - Dana"
        ),
    ),
    _ticket(
        "ticket-002",
        "Leo",
        "leo@example.test",
        "Archive Hoodie return",
        ("Order #48214 does not fit. I wore it once indoors and would like a refund."),
    ),
    _ticket(
        "ticket-003",
        "Maya",
        "maya@example.test",
        "Return my tote",
        ("The unused Everyday Tote from order #48215 is not for me. Please refund it."),
    ),
    _ticket(
        "ticket-004",
        "Sam",
        "sam@example.test",
        "Cracked carry-on",
        (
            "The shell on my Aluminum Carry-On from order #48216 cracked "
            "on first use. Please refund the $280 purchase."
        ),
    ),
    _ticket(
        "ticket-005",
        "Priya",
        "priya@example.test",
        "Refund missing order",
        "Please refund order #99999. The item was never what I expected.",
    ),
    _ticket(
        "ticket-006",
        "Chris",
        "chris@example.test",
        "Backpack never arrived",
        (
            "Order #48217 has not arrived. Tracking has not moved and I "
            "need a replacement."
        ),
    ),
    _ticket(
        "ticket-007",
        "Morgan",
        "morgan@example.test",
        "Defective jacket refund",
        (
            "The zipper broke on the Field Jacket from order #48218. "
            "Refund it today, please."
        ),
    ),
    _ticket(
        "ticket-008",
        "Alex",
        "alex@example.test",
        "Still waiting for refund",
        (
            "Please refund order #48219 again. I cannot see the earlier "
            "refund on my card."
        ),
    ),
    _ticket(
        "ticket-009",
        "Jamie",
        "jamie@example.test",
        "Wrong color tees",
        (
            "Order #48220 arrived in the wrong color. Please refund $120 "
            "for the inconvenience."
        ),
    ),
    _ticket(
        "ticket-010",
        "Riley",
        "riley@example.test",
        "Wrong order number, defective shoes",
        (
            "I think my order is #48228, but it may be under this email. "
            "My Merino Runners arrived with a torn seam and I want a refund."
        ),
    ),
)

DEMO_CASES = (
    _ticket(
        "ticket-101",
        "Nora",
        "nora@example.test",
        "Duffel strap tore off",
        "The shoulder strap tore off my Weekender Duffel (order #48230) on its first trip. Please refund it.",
    ),
    _ticket(
        "ticket-102",
        "Omar",
        "omar@example.test",
        "Sole coming off my boots",
        "The sole is separating on the Leather Chelsea Boots from order #48231 after two wears. I want my money back.",
    ),
    _ticket(
        "ticket-103",
        "Ines",
        "ines@example.test",
        "Parka seam split",
        "The side seam on my Down Parka (order #48232) split and feathers are coming out. Please refund the full amount.",
    ),
    _ticket(
        "ticket-104",
        "Theo",
        "theo@example.test",
        "Wheel snapped off",
        "A wheel snapped off the Hardshell Checked Bag from order #48233 at the airport. I need a refund.",
    ),
    _ticket(
        "ticket-105",
        "Lena",
        "lena@example.test",
        "Broken buckle",
        "The buckle on my Leather Messenger Bag (order #48234) broke within a week. Refund please.",
    ),
    _ticket(
        "ticket-106",
        "Kofi",
        "kofi@example.test",
        "Torn upper on trail shoes",
        "The upper tore on my Trail Running Shoes, order #48235, on the second run. I'd like a refund.",
    ),
    _ticket(
        "ticket-107",
        "Yuki",
        "yuki@example.test",
        "Overcoat lining torn",
        "My Wool Overcoat from order #48236 arrived with the lining torn at the sleeve. Please refund it.",
    ),
    _ticket(
        "ticket-108",
        "Ben",
        "ben@example.test",
        "Sneakers glue failed",
        "The glue failed on the toe cap of my Canvas Sneakers (order #48237). Can I get a refund?",
    ),
    _ticket(
        "ticket-109",
        "Ava",
        "ava@example.test",
        "Holes in new socks",
        "Two of the three pairs in order #48238 have holes at the heel. Please refund.",
    ),
    _ticket(
        "ticket-110",
        "Luis",
        "luis@example.test",
        "Wallet stitching unravelled",
        "The stitching on the Card Wallet from order #48239 unravelled after a few days. I'd like a refund.",
    ),
    _ticket(
        "ticket-111",
        "Zoe",
        "zoe@example.test",
        "Rain jacket leaks",
        "My Rain Jacket (order #48240) leaks through the shoulder seams. Please refund it.",
    ),
    _ticket(
        "ticket-112",
        "Finn",
        "finn@example.test",
        "Cabin tote zipper broke",
        "The main zipper on the Cabin Tote from order #48241 broke. Refund please.",
    ),
    _ticket(
        "ticket-113",
        "Mia",
        "mia@example.test",
        "Sandal strap snapped",
        "The strap snapped on my Slip-On Sandals, order #48242. I want a refund.",
    ),
    _ticket(
        "ticket-114",
        "Raj",
        "raj@example.test",
        "Beanie unravelling",
        "The Knit Beanie from order #48243 is unravelling at the crown. Please refund.",
    ),
    _ticket(
        "ticket-115",
        "Eve",
        "eve@example.test",
        "Return unworn shirt",
        "The Linen Shirt from order #48244 is unworn with tags on. It is not my style, please refund it.",
    ),
    _ticket(
        "ticket-116",
        "Jon",
        "jon@example.test",
        "Returning unused boots",
        "I never wore the Desert Boots from order #48245. Please refund them.",
    ),
    _ticket(
        "ticket-117",
        "Kim",
        "kim@example.test",
        "Organizer never arrived",
        "Order #48246 never showed up and tracking stopped updating. Please send a replacement.",
    ),
    _ticket(
        "ticket-118",
        "Tom",
        "tom@example.test",
        "Missing shorts",
        "My Running Shorts from order #48247 have not arrived. I need a replacement.",
    ),
    _ticket(
        "ticket-119",
        "Sara",
        "sara@example.test",
        "Daypack lost in the post",
        "Order #48248 seems lost. Tracking has been stuck for two weeks. Please replace it.",
    ),
    _ticket(
        "ticket-120",
        "Dev",
        "dev@example.test",
        "Return my belt",
        "I have not used the Leather Belt from order #48249 and would like to return it for a refund.",
    ),
    _ticket(
        "ticket-121",
        "Amy",
        "amy@example.test",
        "Late return",
        "The Chino Trousers from order #48250 are still unworn. Can I get a refund?",
    ),
    _ticket(
        "ticket-122",
        "Max",
        "max@example.test",
        "Changed my mind",
        "I changed my mind about the Outlet Sneakers in order #48251. Please refund them.",
    ),
    _ticket(
        "ticket-123",
        "Liv",
        "liv@example.test",
        "Refund not received",
        "Please refund order #48252. I still cannot see the refund you promised.",
    ),
    _ticket(
        "ticket-124",
        "Gus",
        "gus@example.test",
        "Where is my order",
        "Order #48253 has not arrived yet. Send me a replacement.",
    ),
)
