replicaCount: 1

image:
  repository: zenmldocker/kitaru
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

server:
  environment: {}
  secretEnvironment: {}
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      memory: 600Mi

service:
  type: ClusterIP
  annotations: {}

httpRoute:
  enabled: false
  annotations: {}
  parentRefs: []
  hostnames: []

nodeSelector: {}
tolerations: []
affinity: {}
