"""Shared constants for the PydanticAI adapter."""

from kitaru._checkpoint_metadata import (
    ADAPTER_CHECKPOINT_KIND_KEY,
    ADAPTER_KEY,
    CHECKPOINT_ORIGIN_KEY,
    REPLAY_INPUT_SLOTS_KEY,
    REPLAY_OUTPUT_SLOTS_KEY,
)

ADAPTER_ID = "pydantic_ai"
ADAPTER_METADATA_KEY = "adapter"

ARTIFACT_ROLE_ARGS = "args"
ARTIFACT_ROLE_PROMPT = "prompt"
ARTIFACT_ROLE_RESPONSE = "response"
ARTIFACT_ROLE_RESULT = "result"
ARTIFACT_ROLE_STREAM_TRANSCRIPT = "stream_transcript"
ARTIFACT_SLOT_MESSAGES = "messages"
ARTIFACT_SLOT_OUTPUT = "output"
ARTIFACT_SLOT_TOOL_ARGS = "tool_args"

ADAPTER_CHECKPOINT_KIND_MODEL_REQUEST = "model_request"
ADAPTER_CHECKPOINT_KIND_MCP_CALL = "mcp_call"
ADAPTER_CHECKPOINT_KIND_TOOL_CALL = "tool_call"
ADAPTER_CHECKPOINT_KIND_TURN = "turn"

__all__ = [
    "ADAPTER_CHECKPOINT_KIND_KEY",
    "ADAPTER_CHECKPOINT_KIND_MCP_CALL",
    "ADAPTER_CHECKPOINT_KIND_MODEL_REQUEST",
    "ADAPTER_CHECKPOINT_KIND_TOOL_CALL",
    "ADAPTER_CHECKPOINT_KIND_TURN",
    "ADAPTER_ID",
    "ADAPTER_KEY",
    "ADAPTER_METADATA_KEY",
    "ARTIFACT_ROLE_ARGS",
    "ARTIFACT_ROLE_PROMPT",
    "ARTIFACT_ROLE_RESPONSE",
    "ARTIFACT_ROLE_RESULT",
    "ARTIFACT_ROLE_STREAM_TRANSCRIPT",
    "ARTIFACT_SLOT_MESSAGES",
    "ARTIFACT_SLOT_OUTPUT",
    "ARTIFACT_SLOT_TOOL_ARGS",
    "CHECKPOINT_ORIGIN_KEY",
    "REPLAY_INPUT_SLOTS_KEY",
    "REPLAY_OUTPUT_SLOTS_KEY",
]
