#  Copyright (c) ZenML GmbH 2026. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at:
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  or implied. See the License for the specific language governing
#  permissions and limitations under the License.
"""Add scoped idempotency records.

Revision ID: 002_add_idempotency_record
Revises: 001_initial
Create Date: 2026-08-04 11:16:05.208422

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "002_add_idempotency_record"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_record",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_account_id", sa.Uuid(), nullable=False),
        sa.Column("actor_principal_kind", sa.String(length=16), nullable=False),
        sa.Column("actor_principal_identity", sa.String(length=96), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("route", sa.String(length=255), nullable=False),
        sa.Column("caller_key", sa.String(length=255), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.LargeBinary(), nullable=True),
        sa.Column(
            "response_headers",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(state = 'pending' AND response_status IS NULL "
            "AND response_body IS NULL AND response_headers IS NULL "
            "AND completed_at IS NULL AND expires_at IS NULL) OR "
            "(state = 'completed' AND response_status BETWEEN 100 AND 599 "
            "AND response_body IS NOT NULL AND response_headers IS NOT NULL "
            "AND completed_at IS NOT NULL AND expires_at > completed_at)",
            name="ck_idempotency_record_state_response_status",
        ),
        sa.CheckConstraint(
            "fingerprint ~ '^[0-9a-f]{64}$'", name="ck_idempotency_record_fingerprint"
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'completed')", name="ck_idempotency_record_state"
        ),
        sa.ForeignKeyConstraint(
            ["actor_account_id"],
            ["account.id"],
            name="fk_idempotency_record_actor_account_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "actor_account_id",
            "actor_principal_kind",
            "actor_principal_identity",
            "method",
            "route",
            "caller_key",
            name="uq_idempotency_record_actor_account_id_actor_principal_kind_act",
        ),
    )
    with op.batch_alter_table("idempotency_record", schema=None) as batch_op:
        batch_op.create_index(
            "ix_idempotency_record_expires_at_id",
            ["expires_at", "id"],
            unique=False,
            postgresql_where=sa.text("state = 'completed' AND expires_at IS NOT NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("idempotency_record", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_idempotency_record_expires_at_id",
            postgresql_where=sa.text("state = 'completed' AND expires_at IS NOT NULL"),
        )

    op.drop_table("idempotency_record")
    # ### end Alembic commands ###
