"""add account and API key

Revision ID: 002_add_account_and_api_key
Revises: 001_initial
Create Date: 2026-07-23 11:53:03.771418

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "002_add_account_and_api_key"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_service_account", sa.Boolean(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "password_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "is_service_account", name="uq_account_name_is_service_account"
        ),
    )
    op.create_table(
        "api_key",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "key_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_used", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_api_key_name"),
    )
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.create_index("ix_api_key_owner_id", ["owner_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_index("ix_api_key_owner_id")

    op.drop_table("api_key")
    op.drop_table("account")
    # ### end Alembic commands ###
