"""add agent

Revision ID: 004_add_agent
Revises: 003_add_secret
Create Date: 2026-07-23 19:19:08.141046

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "004_add_agent"
down_revision = "003_add_secret"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_agent_name"),
    )
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.create_index("ix_agent_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "agent_version",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("run_command", sa.Text(), nullable=True),
        sa.Column("run_working_dir", sa.Text(), nullable=True),
        sa.Column("run_env", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("run_timeout_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agent.id"], name="fk_agent_version_agent_id"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_id", "version", name="uq_agent_version_agent_id_version"
        ),
    )
    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.create_index("ix_agent_version_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "agent_version_secret",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("secret_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_version.id"],
            name="fk_agent_version_secret_agent_version_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["secret_id"], ["secret.id"], name="fk_agent_version_secret_secret_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_version_id",
            "secret_id",
            name="uq_agent_version_secret_agent_version_id_secret_id",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_version_secret")
    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_version_owner_id")

    op.drop_table("agent_version")
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_owner_id")

    op.drop_table("agent")
    # ### end Alembic commands ###
