"""add record replay

Revision ID: 004_add_record_replay
Revises: 003_add_secret
Create Date: 2026-07-23 22:50:00.382241

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "004_add_record_replay"
down_revision = "003_add_secret"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_agent_name"),
    )
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.create_index("ix_agent_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "replay_config",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("override", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "tool_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "scoring_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("replay_config", schema=None) as batch_op:
        batch_op.create_index("ix_replay_config_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "tag",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_tag_name"),
    )
    op.create_table(
        "agent_version",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("run_command", sa.Text(), nullable=True),
        sa.Column("run_working_dir", sa.Text(), nullable=True),
        sa.Column("run_env", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("run_timeout_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agent.id"], name="fk_agent_version_agent_id"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_id", "version", name="uq_agent_version_agent_id_version"
        ),
    )
    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.create_index("ix_agent_version_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "cohort",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("session_count", sa.Integer(), nullable=False),
        sa.Column(
            "filter_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agent.id"], name="fk_cohort_agent_id"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_cohort_name"),
    )
    with op.batch_alter_table("cohort", schema=None) as batch_op:
        batch_op.create_index("ix_cohort_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "tag_link",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resource_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tag_id",
            "resource_type",
            "resource_id",
            name="uq_tag_link_tag_id_resource_type_resource_id",
        ),
    )
    with op.batch_alter_table("tag_link", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tag_link_resource_type_resource_id",
            ["resource_type", "resource_id"],
            unique=False,
        )

    op.create_table(
        "agent_version_secret",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("secret_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_version.id"],
            name="fk_agent_version_secret_agent_version_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["secret_id"], ["secret.id"], name="fk_agent_version_secret_secret_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_version_id",
            "secret_id",
            name="uq_agent_version_secret_agent_version_id_secret_id",
        ),
    )
    op.create_table(
        "experiment",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("replay_config_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"], ["cohort.id"], name="fk_experiment_cohort_id"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replay_config_id"],
            ["replay_config.id"],
            name="fk_experiment_replay_config_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_experiment_name"),
    )
    with op.batch_alter_table("experiment", schema=None) as batch_op:
        batch_op.create_index("ix_experiment_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "session",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "origin", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "external_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            "framework", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "adapter_version",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column("log_uri", sa.Text(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("cached_input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("reasoning_tokens", sa.BigInteger(), nullable=True),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("llm_call_count", sa.Integer(), nullable=False),
        sa.Column("tool_call_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agent.id"], name="fk_session_agent_id"),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_version.id"],
            name="fk_session_agent_version_id",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "external_id", name="uq_session_provider_external_id"
        ),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(
            "ix_session_agent_id_created", ["agent_id", "created"], unique=False
        )
        batch_op.create_index("ix_session_external_id", ["external_id"], unique=False)
        batch_op.create_index("ix_session_origin", ["origin"], unique=False)
        batch_op.create_index("ix_session_owner_id", ["owner_id"], unique=False)
        batch_op.create_index("ix_session_status", ["status"], unique=False)

    op.create_table(
        "cohort_session",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["cohort.id"],
            name="fk_cohort_session_cohort_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], name="fk_cohort_session_session_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cohort_id", "position", name="uq_cohort_session_cohort_id_position"
        ),
        sa.UniqueConstraint(
            "cohort_id", "session_id", name="uq_cohort_session_cohort_id_session_id"
        ),
    )
    with op.batch_alter_table("cohort_session", schema=None) as batch_op:
        batch_op.create_index(
            "ix_cohort_session_session_id", ["session_id"], unique=False
        )

    op.create_table(
        "experiment_run",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("score_baselines", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_version.id"],
            name="fk_experiment_run_agent_version_id",
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiment.id"], name="fk_experiment_run_experiment_id"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "experiment_id", "number", name="uq_experiment_run_experiment_id_number"
        ),
    )
    with op.batch_alter_table("experiment_run", schema=None) as batch_op:
        batch_op.create_index("ix_experiment_run_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "session_node",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "secondary_parent_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "external_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "trace_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "node_type", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "requested_model",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("cached_input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("reasoning_tokens", sa.BigInteger(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column(
            "model_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "tool_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("cache_key", sa.CHAR(length=64), nullable=True),
        sa.Column(
            "subagent_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["session_node.id"],
            name="fk_session_node_parent_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name="fk_session_node_session_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "external_id", name="uq_session_node_session_id_external_id"
        ),
        sa.UniqueConstraint("session_id", "key", name="uq_session_node_session_id_key"),
        sa.UniqueConstraint(
            "session_id", "sequence", name="uq_session_node_session_id_sequence"
        ),
    )
    with op.batch_alter_table("session_node", schema=None) as batch_op:
        batch_op.create_index("ix_session_node_cache_key", ["cache_key"], unique=False)

    op.create_table(
        "replay",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_run_id", sa.Uuid(), nullable=True),
        sa.Column("replay_config_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("original_session_id", sa.Uuid(), nullable=False),
        sa.Column("result_session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "worker_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_version.id"],
            name="fk_replay_agent_version_id",
        ),
        sa.ForeignKeyConstraint(
            ["experiment_run_id"],
            ["experiment_run.id"],
            name="fk_replay_experiment_run_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["original_session_id"],
            ["session.id"],
            name="fk_replay_original_session_id",
        ),
        sa.ForeignKeyConstraint(
            ["replay_config_id"],
            ["replay_config.id"],
            name="fk_replay_replay_config_id",
        ),
        sa.ForeignKeyConstraint(
            ["result_session_id"], ["session.id"], name="fk_replay_result_session_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "experiment_run_id",
            "original_session_id",
            name="uq_replay_experiment_run_id_original_session_id",
        ),
    )
    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.create_index(
            "ix_replay_experiment_run_id_status",
            ["experiment_run_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            "ix_replay_original_session_id", ["original_session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.drop_index("ix_replay_original_session_id")
        batch_op.drop_index("ix_replay_experiment_run_id_status")

    op.drop_table("replay")
    with op.batch_alter_table("session_node", schema=None) as batch_op:
        batch_op.drop_index("ix_session_node_cache_key")

    op.drop_table("session_node")
    with op.batch_alter_table("experiment_run", schema=None) as batch_op:
        batch_op.drop_index("ix_experiment_run_owner_id")

    op.drop_table("experiment_run")
    with op.batch_alter_table("cohort_session", schema=None) as batch_op:
        batch_op.drop_index("ix_cohort_session_session_id")

    op.drop_table("cohort_session")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index("ix_session_status")
        batch_op.drop_index("ix_session_owner_id")
        batch_op.drop_index("ix_session_origin")
        batch_op.drop_index("ix_session_external_id")
        batch_op.drop_index("ix_session_agent_id_created")

    op.drop_table("session")
    with op.batch_alter_table("experiment", schema=None) as batch_op:
        batch_op.drop_index("ix_experiment_owner_id")

    op.drop_table("experiment")
    op.drop_table("agent_version_secret")
    with op.batch_alter_table("tag_link", schema=None) as batch_op:
        batch_op.drop_index("ix_tag_link_resource_type_resource_id")

    op.drop_table("tag_link")
    with op.batch_alter_table("cohort", schema=None) as batch_op:
        batch_op.drop_index("ix_cohort_owner_id")

    op.drop_table("cohort")
    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_version_owner_id")

    op.drop_table("agent_version")
    op.drop_table("tag")
    with op.batch_alter_table("replay_config", schema=None) as batch_op:
        batch_op.drop_index("ix_replay_config_owner_id")

    op.drop_table("replay_config")
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_owner_id")

    op.drop_table("agent")
    # ### end Alembic commands ###
