"""add account external_id

Revision ID: 004_add_account_external_id
Revises: 003_add_secret
Create Date: 2026-07-27 10:12:44.281903

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "004_add_account_external_id"
down_revision = "003_add_secret"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("external_id", sa.Uuid(), nullable=True))
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_index("ix_account_external_id", ["external_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_index("ix_account_external_id")

    op.drop_column("account", "external_id")
    # ### end Alembic commands ###
