"""add remote execution

Revision ID: 005_add_remote_execution
Revises: 004_add_record_replay
Create Date: 2026-07-24 16:12:42.979802

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "005_add_remote_execution"
down_revision = "004_add_record_replay"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name="fk_worker_owner_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_worker_name"),
    )
    with op.batch_alter_table("worker", schema=None) as batch_op:
        batch_op.create_index("ix_worker_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "blob",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column(
            "media_type", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("data", sa.LargeBinary(), nullable=True),
        sa.Column("uri", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["account.id"], name="fk_blob_owner_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_blob_sha256"),
    )
    with op.batch_alter_table("blob", schema=None) as batch_op:
        batch_op.create_index("ix_blob_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "plugin",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latest_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name="fk_plugin_owner_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "name", name="uq_plugin_kind_name"),
    )
    with op.batch_alter_table("plugin", schema=None) as batch_op:
        batch_op.create_index(
            "ix_plugin_kind_provider", ["kind", "provider"], unique=False
        )
        batch_op.create_index("ix_plugin_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "plugin_version",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "format", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("blob_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entrypoint", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["blob_id"], ["blob.id"], name="fk_plugin_version_blob_id"
        ),
        sa.ForeignKeyConstraint(
            ["plugin_id"],
            ["plugin.id"],
            name="fk_plugin_version_plugin_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "plugin_id", "version", name="uq_plugin_version_plugin_id_version"
        ),
    )

    op.create_table(
        "job",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("experiment_run_id", sa.Uuid(), nullable=True),
        sa.Column("agent_version_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("parent_job_id", sa.Uuid(), nullable=True),
        sa.Column("plugin_version_id", sa.Uuid(), nullable=True),
        sa.Column("payload_blob_id", sa.Uuid(), nullable=True),
        sa.Column(
            "scorer_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "scorer_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("input_session_id", sa.Uuid(), nullable=True),
        sa.Column("result_session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.Uuid(), nullable=True),
        sa.Column(
            "execution_target",
            sqlmodel.sql.sqltypes.AutoString(length=16),
            nullable=False,
        ),
        sa.Column(
            "executor_handle",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agent.id"], name="fk_job_agent_id"),
        sa.ForeignKeyConstraint(
            ["agent_version_id"], ["agent_version.id"], name="fk_job_agent_version_id"
        ),
        sa.ForeignKeyConstraint(
            ["experiment_run_id"],
            ["experiment_run.id"],
            name="fk_job_experiment_run_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["input_session_id"], ["session.id"], name="fk_job_input_session_id"
        ),
        sa.ForeignKeyConstraint(
            ["parent_job_id"],
            ["job.id"],
            name="fk_job_parent_job_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["payload_blob_id"], ["blob.id"], name="fk_job_payload_blob_id"
        ),
        sa.ForeignKeyConstraint(
            ["plugin_version_id"],
            ["plugin_version.id"],
            name="fk_job_plugin_version_id",
        ),
        sa.ForeignKeyConstraint(
            ["result_session_id"], ["session.id"], name="fk_job_result_session_id"
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"], ["worker.id"], name="fk_job_worker_id", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "experiment_run_id",
            "input_session_id",
            name="uq_job_experiment_run_id_input_session_id",
        ),
        sa.UniqueConstraint(
            "parent_job_id",
            "input_session_id",
            "scorer_name",
            name="uq_job_parent_job_id_input_session_id_scorer_name",
        ),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_experiment_run_id_status",
            ["experiment_run_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            "ix_job_input_session_id", ["input_session_id"], unique=False
        )
        batch_op.create_index("ix_job_parent_job_id", ["parent_job_id"], unique=False)

    op.create_index(
        "ix_job_pending_id",
        "job",
        ["id"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_job_active_heartbeat_at",
        "job",
        [sa.text("coalesce(heartbeat_at, claimed_at)")],
        unique=False,
        postgresql_where=sa.text("status IN ('claimed', 'running')"),
    )

    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_replay_experiment_run_id_status"))
        batch_op.drop_index(batch_op.f("ix_replay_original_session_id"))

    op.drop_table("replay")
    op.create_table(
        "replay",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_run_id", sa.Uuid(), nullable=True),
        sa.Column("replay_config_id", sa.Uuid(), nullable=False),
        sa.Column("input_session_id", sa.Uuid(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_run_id"],
            ["experiment_run.id"],
            name="fk_replay_experiment_run_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["input_session_id"], ["session.id"], name="fk_replay_input_session_id"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name="fk_replay_job_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name="fk_replay_owner_id"
        ),
        sa.ForeignKeyConstraint(
            ["replay_config_id"],
            ["replay_config.id"],
            name="fk_replay_replay_config_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", name="uq_replay_job_id"),
    )
    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.create_index(
            "ix_replay_experiment_run_id", ["experiment_run_id"], unique=False
        )
        batch_op.create_index(
            "ix_replay_input_session_id", ["input_session_id"], unique=False
        )

    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_session_job_id", "job", ["job_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_unique_constraint("uq_session_job_id", ["job_id"])

    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.add_column(sa.Column("run_image", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "run_default_execution_target",
                sqlmodel.sql.sqltypes.AutoString(length=16),
                nullable=True,
            )
        )

    op.execute(
        "UPDATE agent_version SET run_default_execution_target = 'pool' "
        "WHERE run_command IS NOT NULL"
    )

    with op.batch_alter_table("experiment_run", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "execution_target",
                sqlmodel.sql.sqltypes.AutoString(length=16),
                server_default="pool",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "executor_handle",
                sqlmodel.sql.sqltypes.AutoString(length=255),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_constraint("uq_session_job_id", type_="unique")
        batch_op.drop_constraint("fk_session_job_id", type_="foreignkey")
        batch_op.drop_column("job_id")

    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.drop_index("ix_replay_input_session_id")
        batch_op.drop_index("ix_replay_experiment_run_id")

    op.drop_table("replay")
    with op.batch_alter_table("experiment_run", schema=None) as batch_op:
        batch_op.drop_column("executor_handle")
        batch_op.drop_column("execution_target")

    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.drop_column("run_default_execution_target")
        batch_op.drop_column("run_image")

    op.create_table(
        "replay",
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("experiment_run_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("replay_config_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("agent_version_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "original_session_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("result_session_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("attempt", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "worker_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "claimed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "heartbeat_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ended_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("passed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "scores",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "diff",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_version.id"],
            name=op.f("fk_replay_agent_version_id"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_run_id"],
            ["experiment_run.id"],
            name=op.f("fk_replay_experiment_run_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["original_session_id"],
            ["session.id"],
            name=op.f("fk_replay_original_session_id"),
        ),
        sa.ForeignKeyConstraint(
            ["replay_config_id"],
            ["replay_config.id"],
            name=op.f("fk_replay_replay_config_id"),
        ),
        sa.ForeignKeyConstraint(
            ["result_session_id"],
            ["session.id"],
            name=op.f("fk_replay_result_session_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("replay_pkey")),
        sa.UniqueConstraint(
            "experiment_run_id",
            "original_session_id",
            name=op.f("uq_replay_experiment_run_id_original_session_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_replay_original_session_id"),
            ["original_session_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_replay_experiment_run_id_status"),
            ["experiment_run_id", "status"],
            unique=False,
        )

    op.drop_index("ix_job_active_heartbeat_at", table_name="job")
    op.drop_index("ix_job_pending_id", table_name="job")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ix_job_parent_job_id")
        batch_op.drop_index("ix_job_input_session_id")
        batch_op.drop_index("ix_job_experiment_run_id_status")

    op.drop_table("job")
    op.drop_table("plugin_version")
    with op.batch_alter_table("plugin", schema=None) as batch_op:
        batch_op.drop_index("ix_plugin_owner_id")
        batch_op.drop_index("ix_plugin_kind_provider")

    op.drop_table("plugin")
    with op.batch_alter_table("blob", schema=None) as batch_op:
        batch_op.drop_index("ix_blob_owner_id")

    op.drop_table("blob")
    with op.batch_alter_table("worker", schema=None) as batch_op:
        batch_op.drop_index("ix_worker_owner_id")

    op.drop_table("worker")
    # ### end Alembic commands ###
