"""add execution targets

Revision ID: 005_add_execution_targets
Revises: 004_add_record_replay
Create Date: 2026-07-24 13:27:29.884857

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "006_add_execution_targets"
down_revision = "005_add_worker"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.add_column(sa.Column("run_image", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "run_default_execution_target",
                sqlmodel.sql.sqltypes.AutoString(length=16),
                nullable=True,
            )
        )

    op.execute(
        "UPDATE agent_version SET run_default_execution_target = 'pool' "
        "WHERE run_command IS NOT NULL"
    )

    with op.batch_alter_table("experiment_run", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "execution_target",
                sqlmodel.sql.sqltypes.AutoString(length=16),
                server_default="pool",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "executor_handle",
                sqlmodel.sql.sqltypes.AutoString(length=255),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experiment_run", schema=None) as batch_op:
        batch_op.drop_column("executor_handle")
        batch_op.drop_column("execution_target")

    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.drop_column("run_default_execution_target")
        batch_op.drop_column("run_image")

    # ### end Alembic commands ###
