"""add cohort

Revision ID: 007_add_cohort
Revises: 006_add_session
Create Date: 2026-07-23 20:20:12.780458

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "007_add_cohort"
down_revision = "006_add_session"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cohort",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("session_count", sa.Integer(), nullable=False),
        sa.Column(
            "filter_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agent.id"], name="fk_cohort_agent_id"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_cohort_name"),
    )
    with op.batch_alter_table("cohort", schema=None) as batch_op:
        batch_op.create_index("ix_cohort_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "cohort_session",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["cohort.id"],
            name="fk_cohort_session_cohort_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], name="fk_cohort_session_session_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cohort_id", "position", name="uq_cohort_session_cohort_id_position"
        ),
        sa.UniqueConstraint(
            "cohort_id", "session_id", name="uq_cohort_session_cohort_id_session_id"
        ),
    )
    with op.batch_alter_table("cohort_session", schema=None) as batch_op:
        batch_op.create_index(
            "ix_cohort_session_session_id", ["session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cohort_session", schema=None) as batch_op:
        batch_op.drop_index("ix_cohort_session_session_id")

    op.drop_table("cohort_session")
    with op.batch_alter_table("cohort", schema=None) as batch_op:
        batch_op.drop_index("ix_cohort_owner_id")

    op.drop_table("cohort")
    # ### end Alembic commands ###
