"""rename replay to job

Revision ID: 007_rename_replay_to_job
Revises: 006_add_execution_targets
Create Date: 2026-07-24 13:59:49.374642

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "007_rename_replay_to_job"
down_revision = "006_add_execution_targets"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_run_id", sa.Uuid(), nullable=True),
        sa.Column("replay_config_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("original_session_id", sa.Uuid(), nullable=False),
        sa.Column("result_session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "worker_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_version_id"], ["agent_version.id"], name="fk_job_agent_version_id"
        ),
        sa.ForeignKeyConstraint(
            ["experiment_run_id"],
            ["experiment_run.id"],
            name="fk_job_experiment_run_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["original_session_id"], ["session.id"], name="fk_job_original_session_id"
        ),
        sa.ForeignKeyConstraint(
            ["replay_config_id"], ["replay_config.id"], name="fk_job_replay_config_id"
        ),
        sa.ForeignKeyConstraint(
            ["result_session_id"], ["session.id"], name="fk_job_result_session_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "experiment_run_id",
            "original_session_id",
            name="uq_job_experiment_run_id_original_session_id",
        ),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_experiment_run_id_status",
            ["experiment_run_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            "ix_job_original_session_id", ["original_session_id"], unique=False
        )

    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_replay_experiment_run_id_status"))
        batch_op.drop_index(batch_op.f("ix_replay_original_session_id"))

    op.drop_table("replay")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "replay",
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("experiment_run_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("replay_config_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("agent_version_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "original_session_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("result_session_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("attempt", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "worker_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "claimed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "heartbeat_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ended_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("passed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "scores",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "diff",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_version.id"],
            name=op.f("fk_replay_agent_version_id"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_run_id"],
            ["experiment_run.id"],
            name=op.f("fk_replay_experiment_run_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["original_session_id"],
            ["session.id"],
            name=op.f("fk_replay_original_session_id"),
        ),
        sa.ForeignKeyConstraint(
            ["replay_config_id"],
            ["replay_config.id"],
            name=op.f("fk_replay_replay_config_id"),
        ),
        sa.ForeignKeyConstraint(
            ["result_session_id"],
            ["session.id"],
            name=op.f("fk_replay_result_session_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("replay_pkey")),
        sa.UniqueConstraint(
            "experiment_run_id",
            "original_session_id",
            name=op.f("uq_replay_experiment_run_id_original_session_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_replay_original_session_id"),
            ["original_session_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_replay_experiment_run_id_status"),
            ["experiment_run_id", "status"],
            unique=False,
        )

    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ix_job_original_session_id")
        batch_op.drop_index("ix_job_experiment_run_id_status")

    op.drop_table("job")
    # ### end Alembic commands ###
