"""add blob and plugin

Revision ID: 008_add_blob_and_plugin
Revises: 006_add_device
Create Date: 2026-07-29 19:14:22.504510

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "008_add_blob_and_plugin"
down_revision = "009_add_tag_and_worker"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blob",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["account.id"], name="fk_blob_owner_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_blob_sha256"),
    )
    with op.batch_alter_table("blob", schema=None) as batch_op:
        batch_op.create_index("ix_blob_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "plugin",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=255), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latest_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name="fk_plugin_owner_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "name", name="uq_plugin_kind_name"),
    )
    with op.batch_alter_table("plugin", schema=None) as batch_op:
        batch_op.create_index(
            "ix_plugin_kind_provider", ["kind", "provider"], unique=False
        )
        batch_op.create_index("ix_plugin_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "plugin_version",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("display_version", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("blob_id", sa.Uuid(), nullable=True),
        sa.Column("requirement", sa.String(length=255), nullable=True),
        sa.Column("entrypoint", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blob_id"], ["blob.id"], name="fk_plugin_version_blob_id"
        ),
        sa.ForeignKeyConstraint(
            ["plugin_id"],
            ["plugin.id"],
            name="fk_plugin_version_plugin_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "plugin_id", "version", name="uq_plugin_version_plugin_id_version"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plugin_version")
    with op.batch_alter_table("plugin", schema=None) as batch_op:
        batch_op.drop_index("ix_plugin_owner_id")
        batch_op.drop_index("ix_plugin_kind_provider")

    op.drop_table("plugin")
    with op.batch_alter_table("blob", schema=None) as batch_op:
        batch_op.drop_index("ix_blob_owner_id")

    op.drop_table("blob")
    # ### end Alembic commands ###
