"""add tag and worker

Revision ID: 009_add_tag_and_worker
Revises: 006_add_device
Create Date: 2026-07-29 19:15:38.604343

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "009_add_tag_and_worker"
down_revision = "006_add_device"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["account.id"], name="fk_tag_owner_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_tag_name"),
    )
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.create_index("ix_tag_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "worker",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("runtime", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name="fk_worker_owner_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_worker_name"),
    )
    with op.batch_alter_table("worker", schema=None) as batch_op:
        batch_op.create_index("ix_worker_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "tag_link",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name="fk_tag_link_tag_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tag_id",
            "resource_type",
            "resource_id",
            name="uq_tag_link_tag_id_resource_type_resource_id",
        ),
    )
    with op.batch_alter_table("tag_link", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tag_link_resource_type_resource_id",
            ["resource_type", "resource_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag_link", schema=None) as batch_op:
        batch_op.drop_index("ix_tag_link_resource_type_resource_id")

    op.drop_table("tag_link")
    with op.batch_alter_table("worker", schema=None) as batch_op:
        batch_op.drop_index("ix_worker_owner_id")

    op.drop_table("worker")
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_index("ix_tag_owner_id")

    op.drop_table("tag")
    # ### end Alembic commands ###
