"""add cohort

Revision ID: 012_add_cohort
Revises: 010_add_session
Create Date: 2026-07-29 20:41:14.528414

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "012_add_cohort"
down_revision = "011_add_experiment"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cohort",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("session_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agent.id"], name="fk_cohort_agent_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_cohort_name"),
    )
    op.create_table(
        "cohort_session",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["cohort.id"],
            name="fk_cohort_session_cohort_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], name="fk_cohort_session_session_id"
        ),
        sa.PrimaryKeyConstraint("cohort_id", "session_id"),
        sa.UniqueConstraint(
            "cohort_id", "index", name="uq_cohort_session_cohort_id_index"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cohort_session")
    op.drop_table("cohort")
    # ### end Alembic commands ###
