"""add job and task

Revision ID: 014_add_job_and_task
Revises: 013_add_evaluation
Create Date: 2026-07-29 21:41:17.891889

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "014_add_job_and_task"
down_revision = "013_add_evaluation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["account.id"], name="fk_job_owner_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index("ix_job_status", ["status"], unique=False)

    op.create_table(
        "task",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("plugin_version_id", sa.Uuid(), nullable=True),
        sa.Column("payload_blob_id", sa.Uuid(), nullable=True),
        sa.Column("input_session_id", sa.Uuid(), nullable=True),
        sa.Column("result_session_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("on_failure", sa.String(length=16), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("env", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("worker_id", sa.Uuid(), nullable=True),
        sa.Column(
            "inputs",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "result",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agent.id"], name="fk_task_agent_id"),
        sa.ForeignKeyConstraint(
            ["agent_version_id"], ["agent_version.id"], name="fk_task_agent_version_id"
        ),
        sa.ForeignKeyConstraint(
            ["input_session_id"], ["session.id"], name="fk_task_input_session_id"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name="fk_task_job_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["payload_blob_id"], ["blob.id"], name="fk_task_payload_blob_id"
        ),
        sa.ForeignKeyConstraint(
            ["plugin_version_id"],
            ["plugin_version.id"],
            name="fk_task_plugin_version_id",
        ),
        sa.ForeignKeyConstraint(
            ["result_session_id"], ["session.id"], name="fk_task_result_session_id"
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"], ["worker.id"], name="fk_task_worker_id", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_id",
            "input_session_id",
            "plugin_version_id",
            name="uq_task_job_id_input_session_id_plugin_version_id",
        ),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(
            "ix_task_heartbeat_at_claimed_at",
            [sa.literal_column("coalesce(heartbeat_at, claimed_at)")],  # ty: ignore[invalid-argument-type]
            unique=False,
            postgresql_where=sa.text("status IN ('claimed', 'running')"),
        )
        batch_op.create_index(
            "ix_task_id",
            ["id"],
            unique=False,
            postgresql_where=sa.text("status = 'pending'"),
        )
        batch_op.create_index(
            "ix_task_input_session_id", ["input_session_id"], unique=False
        )
        batch_op.create_index(
            "ix_task_job_id_status", ["job_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_task_labels",
            ["labels"],
            unique=False,
            postgresql_using="gin",
            postgresql_where=sa.text("status = 'pending'"),
        )

    with op.batch_alter_table("evaluation", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_evaluation_task_id", "task", ["task_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_session_task_id",
            "task",
            ["task_id"],
            ["id"],
            ondelete="SET NULL",
            use_alter=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_constraint("fk_session_task_id", type_="foreignkey")

    with op.batch_alter_table("evaluation", schema=None) as batch_op:
        batch_op.drop_constraint("fk_evaluation_task_id", type_="foreignkey")

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_task_labels",
            postgresql_using="gin",
            postgresql_where=sa.text("status = 'pending'"),
        )
        batch_op.drop_index("ix_task_job_id_status")
        batch_op.drop_index("ix_task_input_session_id")
        batch_op.drop_index(
            "ix_task_id", postgresql_where=sa.text("status = 'pending'")
        )
        batch_op.drop_index(
            "ix_task_heartbeat_at_claimed_at",
            postgresql_where=sa.text("status IN ('claimed', 'running')"),
        )

    op.drop_table("task")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ix_job_status")

    op.drop_table("job")
    # ### end Alembic commands ###
