"""add replay

Revision ID: 015_add_replay
Revises: 014_add_job_and_task
Create Date: 2026-07-30 00:51:25.909507

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "015_add_replay"
down_revision = "014_add_job_and_task"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiment_run",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("evaluate_baselines", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_version.id"],
            name="fk_experiment_run_agent_version_id",
        ),
        sa.ForeignKeyConstraint(
            ["cohort_id"], ["cohort.id"], name="fk_experiment_run_cohort_id"
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiment.id"], name="fk_experiment_run_experiment_id"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name="fk_experiment_run_owner_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "experiment_id", "number", name="uq_experiment_run_experiment_id_number"
        ),
    )
    op.create_table(
        "replay",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_run_id", sa.Uuid(), nullable=True),
        sa.Column("replay_config_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_session_id", sa.Uuid(), nullable=False),
        sa.Column("evaluate_baselines", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["baseline_session_id"],
            ["session.id"],
            name="fk_replay_baseline_session_id",
        ),
        sa.ForeignKeyConstraint(
            ["experiment_run_id"],
            ["experiment_run.id"],
            name="fk_replay_experiment_run_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name="fk_replay_job_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name="fk_replay_owner_id"
        ),
        sa.ForeignKeyConstraint(
            ["replay_config_id"],
            ["replay_config.id"],
            name="fk_replay_replay_config_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "experiment_run_id",
            "baseline_session_id",
            name="uq_replay_experiment_run_id_baseline_session_id",
        ),
        sa.UniqueConstraint("job_id", name="uq_replay_job_id"),
    )
    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.create_index(
            "ix_replay_baseline_session_id", ["baseline_session_id"], unique=False
        )
        batch_op.create_index(
            "ix_replay_experiment_run_id_status",
            ["experiment_run_id", "status"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("replay", schema=None) as batch_op:
        batch_op.drop_index("ix_replay_experiment_run_id_status")
        batch_op.drop_index("ix_replay_baseline_session_id")

    op.drop_table("replay")
    op.drop_table("experiment_run")
    # ### end Alembic commands ###
