{{- if .Values.kitaru.apiKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kitaru-worker.fullname" . }}
  labels:
    {{- include "kitaru-worker.labels" . | nindent 4 }}
data:
  KITARU_API_KEY: {{ .Values.kitaru.apiKey | b64enc | quote }}
{{- end }}
