"""Run the document agent and export real Langfuse traces."""

import argparse
import asyncio
import json
import os
import time
from pathlib import Path
from typing import Any

from pydantic_ai import Agent

from examples.canonical_example.agent import MODEL, build_agent, build_prompt
from examples.canonical_example.corpus import CASES

PROMPTS = {
    "catalog": "Extract the catalog record for this document.",
    "cover": "Read the cover and framework overview, then extract the catalog record.",
    "fields": (
        "Return the full title, publication identifier, publication month, and "
        "top-level framework functions."
    ),
    "concise": "Create a concise structured catalog entry for this standards PDF.",
}
REQUEST_OPTIONS = {"timeout_in_seconds": 30, "max_retries": 3}
REDACTED_EXPORT_FIELDS = {"public_key"}


def _require_environment() -> None:
    """Raise a focused error when tracing credentials are absent."""
    required = (
        "OPENAI_API_KEY",
        "LANGFUSE_PUBLIC_KEY",
        "LANGFUSE_SECRET_KEY",
    )
    missing = [name for name in required if not os.environ.get(name)]
    if missing:
        raise RuntimeError(f"Set {', '.join(missing)} in .env before continuing.")


def _sanitize_export(value: Any) -> Any:
    """Remove credential-shaped telemetry fields from an exported trace."""
    if isinstance(value, dict):
        return {
            key: _sanitize_export(item)
            for key, item in value.items()
            if key not in REDACTED_EXPORT_FIELDS
        }
    if isinstance(value, list):
        return [_sanitize_export(item) for item in value]
    return value


def _get_trace(client: Any, trace_id: str) -> Any:
    """Wait until one flushed trace is queryable through Langfuse."""
    deadline = time.monotonic() + 180
    while True:
        try:
            trace = client.api.trace.get(
                trace_id,
                request_options=REQUEST_OPTIONS,
            )
            if trace.observations:
                return trace
        except Exception:
            if time.monotonic() >= deadline:
                raise
        if time.monotonic() >= deadline:
            raise RuntimeError(
                f"Langfuse trace {trace_id} was not queryable after 180 seconds."
            )
        time.sleep(2)


def _get_expected_session_ids() -> set[str]:
    """Return the 12 Langfuse session IDs generated by this example."""
    return {
        f"{case.document_id}-{prompt_name}" for case in CASES for prompt_name in PROMPTS
    }


def _list_existing_traces(client: Any) -> dict[str, str]:
    """List the newest canonical-example trace for each expected session."""
    page = client.api.trace.list(
        limit=100,
        name="standards-document-extraction",
        version="candidate-v1",
        environment="canonical-example",
        request_options=REQUEST_OPTIONS,
    )
    expected = _get_expected_session_ids()
    return {
        trace.session_id: trace.id
        for trace in page.data
        if trace.session_id in expected
    }


def _wait_for_all_traces(client: Any) -> dict[str, str]:
    """Wait until Langfuse lists every expected canonical-example trace."""
    deadline = time.monotonic() + 180
    existing: dict[str, str] = {}
    while True:
        try:
            existing = _list_existing_traces(client)
            if existing.keys() >= _get_expected_session_ids():
                return existing
        except Exception:
            if time.monotonic() >= deadline:
                raise
        if time.monotonic() >= deadline:
            missing = _get_expected_session_ids() - existing.keys()
            names = ", ".join(sorted(missing))
            raise RuntimeError(f"Langfuse did not receive these traces: {names}")
        time.sleep(2)


async def generate_traces(export_path: Path) -> Path:
    """Run 12 document extractions and write their Langfuse traces as JSONL."""
    _require_environment()
    from langfuse import Langfuse, propagate_attributes

    langfuse = Langfuse()
    Agent.instrument_all()
    agent = build_agent(MODEL)
    existing = await asyncio.to_thread(_list_existing_traces, langfuse)

    for case in CASES:
        for prompt_name, prompt in PROMPTS.items():
            trace_input = case.get_input(prompt).model_dump(mode="json")
            session_id = f"{case.document_id}-{prompt_name}"
            if session_id in existing:
                continue
            with (
                propagate_attributes(
                    session_id=session_id,
                    trace_name="standards-document-extraction",
                    environment="canonical-example",
                    version="candidate-v1",
                    tags=[
                        "document-processing",
                        "kitaru-example",
                        prompt_name,
                    ],
                    metadata={
                        "document_id": case.document_id,
                        "prompt_variant": prompt_name,
                        "source_url": case.url,
                        "source_sha256": case.sha256,
                    },
                ),
                langfuse.start_as_current_observation(
                    name="extract-document",
                    as_type="agent",
                    input=trace_input,
                ) as root,
            ):
                result = await agent.run(build_prompt(case.path, prompt))
                output = result.output.model_dump(mode="json")
                root.update(output=output)
                root.set_trace_io(input=trace_input, output=output)
                trace_id = langfuse.get_current_trace_id()
                if trace_id is None:
                    raise RuntimeError("Langfuse did not create a trace ID.")
            langfuse.flush()

    langfuse.flush()
    existing = await asyncio.to_thread(_wait_for_all_traces, langfuse)
    traces = []
    for session_id in sorted(existing):
        trace = await asyncio.to_thread(_get_trace, langfuse, existing[session_id])
        traces.append(trace)
    export_path.parent.mkdir(parents=True, exist_ok=True)
    export_path.write_text(
        "\n".join(
            json.dumps(_sanitize_export(trace.model_dump(mode="json", by_alias=True)))
            for trace in traces
        )
        + "\n"
    )
    return export_path


def _get_args() -> argparse.Namespace:
    """Parse the trace export destination."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="Destination JSONL trace export.")
    return parser.parse_args()


if __name__ == "__main__":
    asyncio.run(generate_traces(_get_args().output))
